apiVersion: v1
kind: Pod
metadata:
  name: node-afinity-pod
spec:
  containers:
  - name: my-container
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operater: In
            values:
            - ssd
